apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  selector:
    app: node-exporter
  ports:
  - name: http
    port: 9100
    targetPort: 9100
