apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'jenkins-jmx'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['jenkins-service:9400']
    - job_name: 'k8s-nodes'
      static_configs:
      - targets: ['node-exporter:9100']