# Deploy do container com Jenkins expondo a porta 8080 para os caminhos /jenkins e /jolokia e 9400 para jxm exporter no caminho /metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
      #utilizando a imagem criada
        image: jenkins_jolokia:1.0
        ports:
        - containerPort: 8080 # /jenkins e /jolokia
        - containerPort: 9400 # /metrics
